### ISSUE TITLE
Problemes with FDSN retrieving data (single, bulk & parallel)

### ISSUE THREAD

**Issue by john-robert** [kasra-hosseini/obspyDMT#16]
Hi,

I encountered several things:

**1. problem:**

Making a bulk request at RESIF center to retieve data, using:

```obspyDMT --net YV --sta RR*,ETAN,SGIL,.. --min_date .. --max_date .. --event_catalog 'NEIC  --fdsn_base_url RESIF --fdsn_user .. --fdsn_pass ..  --fdsn_bulk  --req_parallel --req_np 10```

It's printed into shell:

> [1/1-4/132-*] saving Response for: YV.ETAN.00.HHE  ---> DONE
[1/1-4/132-*] saving Metadata for: YV.ETAN.00.HHE  ---> DONE
[1/1-6/132-*] saving Response for: YV.ETAN.00.HHN  ---> DONE
[1/1-6/132-*] saving Metadata for: YV.ETAN.00.HHN  ---> DONE

 .. and ..

> [1/1-8/132-*] Response---YV.ETAN.00.HHZ
ERROR: fdsn -- Response---1-8---YV.ETAN.00.HHZ---<urlopen error [Errno 111] Connection refused

> [1/1-7/132-*] Response---YV.ETAN.00.HHN
ERROR: fdsn -- Response---1-7---YV.ETAN.00.HHN---<urlopen error [Errno 111] Connection refused

> [1/1-5/132-*] Response---YV.ETAN.00.HHE
ERROR: fdsn -- Response---1-5---YV.ETAN.00.HHE---<urlopen error [Errno 111] Connection refused

> [1/1-8/132-*] Response---YV.ETAN.00.HHZ
ERROR: fdsn -- Response---1-8---YV.ETAN.00.HHZ---<urlopen error [Errno 111] Connection refused

However, using the same command without bulk or parallel I can retrieve all desired information just nicely. Also, executing the very same command (as above) an hour later lead to different results (less successful downloads). I thus suppose a server error (perhaps bulkdataselect) to be the reason for this but I am not sure. Would this problem already be known ?

---

**2. problem**

Using *--fdsn_update** mode to retrieve missing information as follows:

``` obspyDMT --net YV --sta ETAN --fdsn_base_url RESIF --fdsn_user .. --fdsn_pass ..  --fdsn_update .. --waveform N ```

I sometimes (and the other sometimes not) receive the following error, altought the commands have been identical:

> Traceback (most recent call last):
  File "/usr/local/bin/obspyDMT", line 9, in <module>
    load_entry_point('obspyDMT==0.7.6', 'console_scripts', 'obspyDMT')()
  File "build/bdist.linux-x86_64/egg/obspyDMT/obspyDMT.py", line 5139, in main
  File "build/bdist.linux-x86_64/egg/obspyDMT/obspyDMT.py", line 175, in obspyDMT
  File "build/bdist.linux-x86_64/egg/obspyDMT/obspyDMT.py", line 3376, in FDSN_update
  File "build/bdist.linux-x86_64/egg/obspyDMT/obspyDMT.py", line 4549, in rm_duplicate
IndexError: list assignment index out of range

This problem occurs also when using *--identity* flag, a '*', some or a lot of stations. I also think this is a server error but I am not sure.

---

I am hoping we could suss out the reasons for these errors and, eventually, contact the RESIF data centre with a useable error discription. At least it would be nice to confirm that these errors are not caused by obspyDMT itself.

**Comment by kasra-hosseini** [comment]
Hi John,

Good points! Some comments below:
**1. Problem**
As you mentioned, this is due to the server error and once I mentioned in RHUM-RUM git that RESIF asked to not send parallel requests with more than 4 at the same time. See: https://github.com/rhum-rum/RHUM-RUM/issues/4#issuecomment-64408193

I asked them at that moment but it seems that they can not manage lots of requests at once. Annoying...

**2. Problem**
I think this is also due to the server error that does not give back the available stations correctly for updating. I am sure that this problem does not happen that often from other servers like IRIS. However, maybe we should include an Exception to handle this situation (if the length of the stations got from the server is 0) in order to generate some meaningful errors. Since you have experience with that, do you think you can implement this? if not, I will take care of it soon.

All best,
Kasra

**Comment by john-robert** [comment]
Hi Kasra,

so indeed, the problem was already known. But merci pour taking time explaining it to me again. 
For handling the exception I could implement these couple of lines in the code. Consider it done!

**Comment by kasra-hosseini** [comment]
Hi John,

Thanks for that! I also looked into the code today and changed slightly those parts that you implemented in the events, summary:
1. take out the functions written inside another function and put them as a separate function
2. change the event depth to km (I guess it used to be like that?)

Just one quick point: In case that you are changing the behavior of the outputs, i.e. changing the depth from km to m or etc. It would be great if you can highlight that in a separate commit. This is specifically important since there are some codes built upon the current outputs and if we change those, it would cause some problems. In case of adding a functionality, it would be also nice to keep the outputs similar to what we have (this is indeed the case in the functions that you have written so far, just to emphasize). However, when we want to change the output, this is another story and we will highlight it in the code. I did not find any changes in the output than event depth, are you aware of any?

Many thanks for all your coding and testing.

All best,
Kasra

**Comment by john-robert** [comment]
It's indeed true that I change the events depths from km to meter.
I did this for testing purposes. I must have forgotten to put it back. Desolé.

Thank you for the advices. I'll keep them in mind.

**Comment by john-robert** [comment]
Well, I just remember that I changed the names of the ouput files in the 'EVENTS-INFO' folder (I introduced also new files).
I actually did not recognise any errors/problems due to that but maybe because I didnt't caught all scenarios.

**Comment by kasra-hosseini** [comment]
I guess it should not make any problem. I checked the code and we only have EVENTS-INFO for logging purposes and not using anything from there anymore in the code. Adding new files is perfectly fine, my point was only about existing files. Otherwise, more useful information is always welcome and does not hurt the code since they had not been used originally.
