### ISSUE TITLE
'NoneType' error with --event_info

### ISSUE THREAD

**Issue by mary-tsekhmistrenko** [kasra-hosseini/obspyDMT#23]
Hi Kasra,

I had an issue with the following command line:

``` python
obspyDMT --event_info --datapath /Users/maria/PhD/Codes/EVENTS_Overview/Overview --min_mag 3.0 --max_mag 5.9 --min_date 2012-09-25 --max_date 2013-12-05 --event_catalog NEIC_USGS
```

Apparently the _obspy_ plotting tool cannot handle events that have **'NoneType'**, because with 

``` python
obspyDMT --seismicity --datapath /Users/maria/PhD/Codes/EVENTS_Overview/Overview --min_mag 3.0 --max_mag 5.9 --min_date 2012-09-25 --max_date 2013-12-05 --event_catalog NEIC_USGS
```

it actually works again, but gives some warnings:

``` python
WARNING: half_duration does not exist for event: 989 -- set to False
unsupported operand type(s) for /: 'NoneType' and 'float'
```

but doesn't crash.

Any ideas how to fix that?

Cheers,
Maria

**Comment by kasra-hosseini** [comment]
Hi Maria,

Thanks for reporting this issue! As you already mentioned, this is not an issue in obspyDMT but actually from the QuakeML file retrieved from NEIC. As an example, the same command but with different minimum magnitude:

```python
obspyDMT --event_info --min_mag 5.0 --max_mag 5.9 --min_date 2012-09-25 --max_date 2013-12-05 --event_catalog NEIC_USGS
```

so, I just increased the *--min_mag* from 3.0 to 5.0. This command works and here is the outcome:

![event_info](https://cloud.githubusercontent.com/assets/1899856/10253425/9f08184e-693d-11e5-8720-3b4904486088.png)

Please note that *--event_info* option uses obspy tools for plotting the seismicity map. However, *--seismicity* option is a function in *obspyDMT* and it does not plot those events that have problematic information, i.e. it plots all those events that contain all the required information and only raise an exception in case that some information are missing (and of course, do not plot such events).

To solve this problem, one way is to change the plotting tool in obspy to raise exception rather than error. Something similar to *seismicity* in obspyDMT. The other solution is to actually use *seismicity*. Please write me if your preference is the former one, then we should see how easy it is to change the obspy plotting tool. I, personally, would go with *seismicity* option as it generates more or less similar plots as *event_info* option + some statistical analysis + beachballs ;)

Hope this helps.

Cheers,
K
