### ISSUE TITLE
SAC header: missing information

### ISSUE THREAD

**Issue by john-robert** [kasra-hosseini/obspyDMT#9]
When using the following command:

    obspyDMT --identity YV.RR*.*.* --preset 900 --offset 1500 --cut_time_phase --fdsn_base_url RESIF  --fdsn_user .. --fdsn_pass ..

The waveforms of my desired station(s) are downloaded for all events retrieved. Here, for each event and each station the first arrival time is predicted (--cut_time_phase) in order to cut the waveforms before (--preset 900) and after (--offset 1500) this time. 
I chose to save files in the SAC-format (default).

However, the downloaded waveforms are not plotted with absolute time axis but relative ones, e.g. from 0 to 2400 (900 + 1500). 

I now need the offset between the earthquake origin time and the begin of the downloaded time window. In SAC headers, this offset is referred to as:

**O (Event origin time - seconds relative to reference time)** 

and its value is basically **"cut_time_phase" - "preset"** (float - single precise). As I see it, this information is not written to SAC headers by obspyDMT and it therefore is not possible to refer the downloaded files to absolute times.

Can you confirm this and if so, would you be able to make a commit on this quickly ? (shouldn't take you longer than ten minutes, myself, however, would need unequally longer) 
Over christmas, I'd like to run some calculations and would therefore need this infomation. Surely, I could make a (dirty) workaround but would rather prefer ..

[SAC header information](http://ds.iris.edu/files/sac-manual/manual/file_format.html)
[SAC commands](http://seismolab.gso.uri.edu/~savage/sac/commands/func_commands.html)

Frohe Weihnacht & Merci

**Comment by john-robert** [comment]
Hi Kasra,

thanks for your answer. No worries for the 'late' reply, I actually hoped you would make some holidays. :) I can confirm that obspyDMT does put the header information as you stated:

**station:** latitude, longitude, elevation and burrial
**event:** latitude, longitude, depth and magnitude

Using obspyDMT to download files as sac-files, I can confirm that all the following variables are correctly assigned:

**NZYEAR, NZJDAY, NZHOUR,  NZMIN, NZSEC, NZMSEC, NZDTTM**
**KZTIME** and **KADATE** -- basically a combination of the NZ-variables
**IZTYPE** which you choose to be the GMT begin time of the actual, downloaded trace (meaning: focal time + travel time - preset)

You are right, in that way "O" just takes the value of "preset", as KZTIME already implies the travel times values. Does that make sense?

So I propose that you could just adabt the code the way that obspyDMT assigns the "preset" value to "O" and everything is fine. Fabrice does agree with that.
It is, as you stated, basically a question of correct definition and as obspyDMT does correctly assign tte IZTYPE-variable there should be no problems. However, having "O" inside correctly would allow to use already exiting SAC-macros, e.g to plot theoretical arrival times to make phase pickings more convinient.

Surely, assigning "A" using automatic pick routines would be a real nice thing, I'd love it. I had a quick look to obspy, there is already a lot implemented. Sounds like an *ISSUE*.

Before you plan to change anything, I'd like you to wait a couple of days more, as I a planning to commit my obspyDMT.py changes like this week. There would be a lot of changes which would needed to be tested extensively (which I did but still) and also receive your blessing. ;)

So maybe before it's time to change this, it's time to merge and clear. Just an idea.

Bis dahin
John

**Comment by kasra-hosseini** [comment]
Hi John,

Thanks for your message. Some comments below:

**in that way "O" just takes the value of "preset", as KZTIME already implies the travel times values. Does that make sense?**
Let me see:
Time-wise and only for one example, we have the following time flags:
Origin-time ----- start time of the trace ----- phase ----- rest of the seismogram -----

KZTIME is the begin time of the actual data, in other words:
Origin-time ----- start time of the trace (KZTIME) ----- phase ----- rest of the seismogram -----

Definition of O is Event origin time (relative to the reference time), and the reference time here is KZTIME. Therefore, O should be (Origin_time - KZTIME)? "A" flag will be **preset** and etc. This is different from assigning 'preset' value to 'O'; however, I am not quite sure. What do you think?

**However, having "O" inside correctly would allow to use already exiting SAC-macros, e.g to plot theoretical arrival times to make phase pickings more convinient.**
I totally understand this and I will definitely do that once we reach to an agreement on the definition of the headers. (which I guess it will happen soon).

**Surely, assigning "A" using automatic pick routines would be a real nice thing, I'd love it. I had a quick look to obspy, there is already a lot implemented. Sounds like an ISSUE.**
It is indeed an issue, but "A" can be only the theoretical arrival time which is very easy to implement (we already have it in obspyDMT). I think some codes like rdseed and etc also only fill in the theoretical arrival times rather than automatic pick routines...

**Before you plan to change anything, I'd like you to wait a couple of days more, as I a planning to commit my obspyDMT.py changes like this week. There would be a lot of changes which would needed to be tested extensively (which I did but still) and also receive your blessing. ;)**
Sounds interesting! I am looking forward for your changes and I will merge the new changes + the previous one altogether. I will wait until we are done with merging and cleaning and will apply the SAC header thing afterwards.

All best,
Kasra

**Comment by kasra-hosseini** [comment]
Can you update me about this issue as well?

**Comment by john-robert** [comment]
I just recognised that stored SAC files based on retrieved events (form  both online/offline catalogues) do miss the header information **STDP**.
Following [Iris_sac_manual](http://ds.iris.edu/files/sac-manual/manual/file_format.html) the option (and a couple of others) is:
> [not currently used]

Still, it may not be the worsed the include at least this information (maybe STEL, too) as I do not see any disadvantage and it's nice to have it there and check quickly. There is no priority.

For the other options (-A, -O, ..) I will make another comment in the near future.

**Comment by kasra-hosseini** [comment]
Are you sure about this? I just checked it with --tour flag and here is what I got:

```python
cd ./dmt-tour-data/2011-03-11_2011-03-11_9.1_9.1/20110311_1/BH_RAW
from obspy import read
st = read('TA.133A..BHZ', format='SAC')
st[0].stats.sac.stel
Out[4]: 418.0
st[0].stats.sac.stdp
Out[5]: 0.0
```

Can you provide me with one example that you could not get the elevation and depth information?

Thanks,
Kasra

**Comment by john-robert** [comment]
Aaaargh sorry, you are right.
As I was working with OBS I thought the depth of the station must be present as **STDP**. As the entry was not made there but at **STEL** I thought there is no entry at all. I actually thought I checked both header information ...
but no, just did it again for a couple of station and events .. seems all fine. right sign/value, it's good. My bad ;)

**Comment by kasra-hosseini** [comment]
Good to hear that everything is fine and thanks for checking. I do not close this issue since we still have not made our final decision regarding other headers.

Cheers,
Kasra

**Comment by kasra-hosseini** [comment]
After talking/discussing with several people, it seems that it is better to keep the data header as generic as possible, i.e. do not restrict ourselves to one specific convention. Filling in headers can be always done in the processing stages and it seems that it is quite heterogeneous between different groups. Therefore, I leave the current shape of the code but this issue can be still re-opened in case that we find a better solution.
